### ISSUE TITLE
Earplug Instructions button should open a webpage with earplug instructions

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#37]
The URL it should open: https://youtu.be/jVWRCURH3D0?si=7yUM6sl2BmrC4yce

![image](https://github.com/equinor/attenuation-app/assets/22524448/0fe7ab61-e228-4248-98f5-541f053d1e90)

**Comment by tormodAase** [comment]
Awaiting URL from stakeholders

**Comment by KaterynaBasik** [comment]
> Awaiting URL from stakeholders

The URL is added to the description

**Comment by tormodAase** [comment]
A new build should be available in approximately one hour!
`2024.0709.37`
In this build, You should be able to open the ear plug instructions video

**Comment by tormodAase** [comment]
This change is also available in this build, which also contains a fix to [this issue](https://github.com/equinor/attenuation-app/issues/40): `2024.0709.45`

@KaterynaBasik

**Comment by KaterynaBasik** [comment]
Tested (2024.0709.45):
Works as expected
