### ISSUE TITLE
App Icon and Splash screen

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#43]
We need an app icon and splash screen for the app. It should follow the same design principles as our other apps.

App icons: https://www.figma.com/design/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?node-id=2067-12872&t=O6er1buJSvCzCrBE-0

Splash screens: https://www.figma.com/design/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?node-id=1944-14260&t=O6er1buJSvCzCrBE-0

We need only the green variant

**Comment by VetleW** [comment]
[Icon](https://www.figma.com/design/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?node-id=2797-10419&t=TB5hyCLQRTMSRndW-4) is done.

[Splash screens](https://www.figma.com/design/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?node-id=1944-14260&t=aAKD9HCEJWPXJz5O-1) are done.

**Comment by tormodAase** [comment]
@QiJin-Bouvet Ready to test soon!
Build number: `2024.0731.94`

App icon and splash screen should be visible to the user

**Comment by QiJin-Bouvet** [comment]
Tested with build 2024.0731.94
App icon is shown as design.
Splash is shown as design (too fast to see).
