### ISSUE TITLE
When iPad is rotated the Welcome screen is also rotates and not the entire page is visible. We need to disable screen rotation for iPad. It's disabled for iPhones

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#44]

**Comment by tormodAase** [comment]
@KaterynaBasik Should be ready to test soon!
Build number: `2024.0711.56`

**Comment by KaterynaBasik** [comment]
Tested. Works as expected, no rotation on iPad anymore.

**Comment by QiJin-Bouvet** [comment]
Tested build 2024.731.96 with iPad.
Screen rotation is disabled on iPad.
