### ISSUE TITLE
Progress indicator not always updating

### ISSUE THREAD

**Issue by KaterynaBasik** [equinor/attenuation-app#46]
The progress indicator doesn't always update when moving to the next test screen. It occurs when moving to  `Juster lydvolumet sakte til...` screens

## Steps to reproduce
1. Start the test
2. Observe the progress indicator on the `Lydtest venstre øre uten propper` screen
3. Press Spill av button to proceed  to the next screen
4. Observe the progress indicator on the `Juster lydvolumet sakte til...` screen

## Expected behaviour
The progress indicator should move forward

## Actual behaviour
The progress indicator fails to update when moving to the next test screen.

**Comment by dansvend** [comment]
Closed by #33
