### ISSUE TITLE
Set up application insights

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#50]
- Create application insights resource in Azure
- Install application insights packages in repository
- Track relevant information

Application insights should (for now):
- Log the dB difference results anonymously

**Comment by tormodAase** [comment]
Need a resource group before creating application insights resource

**Comment by tormodAase** [comment]
`2024.0716.68`

Ready to test in 20-60 minutes! @KaterynaBasik 
Once you get to the results screen, the app should track the results in application insights.

<img width="621" alt="image" src="https://github.com/user-attachments/assets/cdad8da5-e270-4b9d-98cf-745b538a9df5">

You will find the data under `customDimensions` inside the `Results` event
![image](https://github.com/user-attachments/assets/d13ed5e0-ce9e-47d6-bdfe-08b2e8112c6a)

**Comment by tormodAase** [comment]
It MAY take a few minutes before you see the results in Application Insights after entering the results screen

**Comment by KaterynaBasik** [comment]
Tested (2024.0716.68)
Anonymous results are available in App Insights under the `Result` event:

- [x] Left and right difference results
- [x] Left and right ear results
