### ISSUE TITLE
Feedback screen

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#53]
Design: https://www.figma.com/design/R5ZB5mHiO145XLrA7x7ife/Attenuation--%3E-Design?node-id=535-6421&t=syVIYjbWUqZT6vIj-1

- The user should be able to rate their experience on a scale from 1 to 5.
- The user should be able to give improvement proposals
- The user should be able to skip giving feedback
- Once the user submits feedback, it should be stored in: Application Insights? (TO BE DECIDED)

**Comment by tormodAase** [comment]
The feedback screen I have so far (on iPad mini vs iPhone SE vs iPhone 15 Pro Max)
<img width="1543" alt="image" src="https://github.com/user-attachments/assets/39485afb-2d5b-448e-9a38-7e3931dbad6d">

On small devices (iPhone SE) the content adjusts slightly when the keyboard pops up

https://github.com/user-attachments/assets/3e6a865d-c077-4124-8373-4ea8dd8021e8

**Comment by KaterynaBasik** [comment]
Looks good to me!

**Comment by tormodAase** [comment]
This is ready to rest!
`2024.0718.76`

You can get to the feedback screen by pressing the "Done" button on the results screen.

We unfortunately haven't found a way to verify that the feedback were successfully sent to application insights. We just assume it is successful. This is something we should probably look further into in the future.

You can find feedbacks in application insights. They should be titled "Feedback", and have `rating` and `improvementText` under `customDimensions`
![image](https://github.com/user-attachments/assets/c11e5ab6-6fd6-4012-98cd-d360160487e5)

**Comment by KaterynaBasik** [comment]
Tested (2024.0718.76)

- [x] Feedback screen appears after pressing the `Done` button
- [x] Screen follows the design 
- [x] It's possible to rate their experience on a scale from 1 to 5
- [x] It's possible to give improvement proposals in a text field
- [x] It's possible to skip giving feedback after user press `Send tilbakemelding` button
- [x] `Takk for tilbakemeldingen` message pops up
- [x] Submitted feedback is stored in Application Insights:

     - `Feedback` event has `"rating":"undefined","improvementText":"undefined"` under `customDimensions` when user didn't specify rating and didn't leave a feedback text and pressed `Send tilbakemelding` or `Hopp over`
     -   `Feedback` event has `"rating":"undefined","improvementText":"{feedback text}"` under `customDimensions` when user didn't specify rating and left a feedback text.
     -  `Feedback` event has `"rating":"{number}"` under `customMeasurements` and `"improvementText":"{feedback text}"` under `customDimensions` when user specified rating and added or didn't add a feedback text.
 
![image](https://github.com/user-attachments/assets/b390be79-97e0-4da8-8840-db67507c7e89)

**Improvement suggestions:**

- [ ]  Write `"rating":"{number}"` under  `customDimensions` when user specified rating.
- [ ]  Make `Send tilbakemelding` button disabled by default. Make it active if rating is specified or/and there is a feedback text. In this way we won't log "undefined"  feedbacks
- [ ] Allow the text box to expand vertically or increase it's default size. Currently the text box doesn't expand when a large amount of text is entered. As a result, the upper lineds ot text are not visible. Considering there is enough space on the screen

![image](https://github.com/user-attachments/assets/02a0e289-2122-4575-bffe-edca35ecae96) 
![image](https://github.com/user-attachments/assets/4ad3dab2-ee13-46a1-b85f-551ba4ca03cb)

@dansvend @VetleW

**Comment by dansvend** [comment]
@KaterynaBasik I've made some changes which is ready for testing in `2024.722.80`:
- `Send tilbakemelding` is disabled when there is no rating & no feedback text or the feedback text contains no characters other than spaces.
- The height of the text field has increased 50% when looking at the feedback page and by 400% when you press on the text field to enter your feedback.

**Comment by KaterynaBasik** [comment]
> [@KaterynaBasik](https://github.com/KaterynaBasik) I've made some changes which is ready for testing in `2024.722.80`:
> 
> * `Send tilbakemelding` is disabled when there is no rating & no feedback text or the feedback text contains no characters other than spaces.
> * The height of the text field has increased 50% when looking at the feedback page and by 400% when you press on the text field to enter your feedback.

These improvements has been tested. Looks nice, works good! 

Noticed one more thing. When user keeps the text field emty it is resulted as `"improvementText":"undefined"` under `customDimensions`.
But when user first entered something and then erased all the text it is resulted  as `"improvementText":""` under `customDimensions`. It would be nice to write it as `"undefined"` as well, if possible.

**Comment by dansvend** [comment]
> > [@KaterynaBasik](https://github.com/KaterynaBasik) I've made some changes which is ready for testing in `2024.722.80`:
> > 
> > * `Send tilbakemelding` is disabled when there is no rating & no feedback text or the feedback text contains no characters other than spaces.
> > * The height of the text field has increased 50% when looking at the feedback page and by 400% when you press on the text field to enter your feedback.
> 
> These improvements have been tested. Looks nice, works good!
> 
> Noticed one more thing. When user keeps the text field emty it is resulted as `"improvementText":"undefined"` under `customDimensions`. But when user first entered something and then erased all the text it is resulted as `"improvementText":""` under `customDimensions`. It would be nice to write it as `"undefined"` as well, if possible.

Great! Thanks for testing. I've made the change you requested and this is available for testing in build `2024.722.81`.

**Comment by KaterynaBasik** [comment]
Testing in build 2024.722.81.

- [x] When user first entered something and then erased all the text it is resulted as "improvementText":"undefined" under customDimensions, as expected

Well done, @dansvend
