### ISSUE TITLE
Rating and improvement text is still there if previous user on a shared device skipped sending feedback

### ISSUE THREAD

**Issue by dansvend** [equinor/attenuation-app#58]
Currently when skip sending feedback, the rating and improvement text is stored in the session and will be there after the next test as long as the app is not closed completely before taking a new test. This could result in the next person taking a test on a shared device to just press "Send feedback" with the previous users unintended feedback. Rating and improvement text should therefore be reset everytime the user exits out of the feedback screen, either by sending feedback or skip sending feedback.

**Comment by dansvend** [comment]
@KaterynaBasik This is ready for testing in build `2024.724.85` 🧪

**Comment by KaterynaBasik** [comment]
Tested with build 2024.724.85.
Works as expected. Now the rating and improvement text is not stored in the session when skip sending feedback.

**Comment by dansvend** [comment]
@KaterynaBasik Nice! Thanks for testing 💪
