### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#6]
https://www.figma.com/design/R5ZB5mHiO145XLrA7x7ife/Attenuation--%3E-Design?node-id=208-77032&t=cB6FUqOptwknEexg-1

**Comment by tormodAase** [comment]
I've made an implementation that looks okay on phone, but on iPad it looks a bit weird and empty.

iPhone SE vs iPhone 15 pro max vs iPad mini
<img width="1529" alt="image" src="https://github.com/equinor/attenuation-app/assets/22524448/d6ac93e2-93c9-4597-903c-6730a7a94dcb">

@dansvend @KaterynaBasik what do you think?

**Comment by dansvend** [comment]
> I've made an implementation that looks okay on phone, but on iPad it looks a bit weird and empty.
> 
> 
> 
> iPhone SE vs iPhone 15 pro max vs iPad mini
> 
> <img width="1529" alt="image" src="https://github.com/equinor/attenuation-app/assets/22524448/d6ac93e2-93c9-4597-903c-6730a7a94dcb">
> 
> 
> 
> @dansvend @KaterynaBasik what do you think?

It looks nice! And I think it looks good enough on iPad for people not to think about it💪

**Comment by tormodAase** [comment]
@KaterynaBasik This should be ready for test when you get back to work on Monday!

Build number: `2024.0705.26`

- The welcome page should follow this [design](https://www.figma.com/design/R5ZB5mHiO145XLrA7x7ife/Attenuation--%3E-Design?node-id=341-78836&t=GYZq4UWAJZuCATai-1), with minor adjustments added as comments by Dan during our wednesday meeting
- You should be able to navigate the carousel in the middle of the screen by either pressing the left or right buttons, or swiping left or right.
- The "Start testen" button should navigate you to the test screen (which is not finished yet)
- The "Ørepropp Instruksjoner" button is NOT functional yet. Created new issue for that button: #37

**Comment by KaterynaBasik** [comment]
Tested  (2024.0705.26):

- [ ] The welcome page follows the design
- [ ] the carousel navigation works well 
- [ ] The "Start testen" button navigates to the test screen
- [ ] The Close button on the Test screen navigates to the  welcome screen, but remembers the previous carousel position. When user is back to the Welcome screen from the Test screen the default carousel position should be the first image. https://github.com/equinor/attenuation-app/issues/40

**Comment by KaterynaBasik** [comment]
Tested (2024.0705.45):
@tormodAase 

> * [ ]  When iPad is rotated the Welcome screen is also rotates and not the entire page is visible. We need to disable screen rotation for iPad. It's disabled for iPhones

**Comment by tormodAase** [comment]
@KaterynaBasik Will merge the welcome screen code to main and solve that in a new branch. Created an issue here: #44
