### ISSUE TITLE
dB difference result doesn't log in App Insights

### ISSUE THREAD

**Issue by KaterynaBasik** [equinor/attenuation-app#62]
The logging functionality, implemented in #50  worked good in build `2024.0716.68`  but with the latest builds `2024.724.85`, `2024.724.83` or `2024.724.86` ` Result `events have stopped logging in App Insight, only `Feedback` event are being recorded.

**Comment by tormodAase** [comment]
Some code were accidentally removed when the results screen was properly implemented. I've created a PR to fix it

**Comment by tormodAase** [comment]
@QiJin-Bouvet This is ready to test!
Build number: `2024.0729.90`

After entering the results screen of the app (and waiting a few minutes), you should see an event called `Results` in application insights. `customDimensions` should contain data regarding the results of the test
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/491ae6d5-3d64-435a-bc90-16bb06adc90c">

**Comment by QiJin-Bouvet** [comment]
Tested with Build number: 2024.0729.90
Decibel difference results are logged in App Insights.

![Image](https://github.com/user-attachments/assets/9630667b-3950-4028-9d58-99c4b10965f2)
