### ISSUE TITLE
Results should be rounded to the closest integer

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#69]

**Comment by tormodAase** [comment]
Update: value should be floored, not rounded to nearest integer.
Example: 15.9 -> 15

**Comment by dansvend** [comment]
@QiJin-Bouvet This is ready for testing in build 2024.820.103

**Comment by QiJin-Bouvet** [comment]
Tested with the build above.
The results are shown in integer, not decimal.

![image](https://github.com/user-attachments/assets/ab25327e-bca1-405f-95d5-768b3a270135)

**Comment by dansvend** [comment]
> Tested with the build above. The results are shown in integer, not decimal.
> 
> ![image](https://private-user-images.githubusercontent.com/88656616/359866871-ab25327e-bca1-405f-95d5-768b3a270135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDMxMjYsIm5iZiI6MTcyNDI0MjgyNiwicGF0aCI6Ii84ODY1NjYxNi8zNTk4NjY4NzEtYWIyNTMyN2UtYmNhMS00MDVmLTk1ZDUtNzY4YjNhMjcwMTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEyMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2NlNTc5OWM0YmQ4ODBjMjBiMGEyNzIyMjk1ZjU3M2I0NjgwZDllYTc0Nzc2ZDk4NTk1YzRlYTk4OTc0N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.26BM3QWPni5jJSuTy9k-KzvnBLlmh7WxUTkUlrHN_mU)

Thanks for testing 💪
