### ISSUE TITLE
Highlight "Begge"/"both" on the "put earplugs into both ears" screen 

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#71]

**Comment by dansvend** [comment]
@QiJin-Bouvet This is ready for testing in `2024.820.104` 🧪

**Comment by QiJin-Bouvet** [comment]
Tested with the build above.
Text 'begge' is highlighted.

![image](https://github.com/user-attachments/assets/f2e40682-ff40-4890-a169-dde88c0110ec)

**Comment by dansvend** [comment]
> Tested with the build above. Text 'begge' is highlighted.
> 
> ![image](https://private-user-images.githubusercontent.com/88656616/359864110-f2e40682-ff40-4890-a169-dde88c0110ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDMxNzYsIm5iZiI6MTcyNDI0Mjg3NiwicGF0aCI6Ii84ODY1NjYxNi8zNTk4NjQxMTAtZjJlNDA2ODItZmY0MC00ODkwLWExNjktZGRlODhjMDExMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEyMjExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4Yjg5N2ZlZDY5ZDhiNGNkODU3MWNkODU3YzViZDc3M2ZhNmU4YTFmMGVkNzVhMzBmMTU1MDlkOTQ0MmUxZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EPo_hBV3EPC8LLDSQYbB4WfaHHoow3Wccv3DMFSNJHg)

Thanks for testing 🙏
