### ISSUE TITLE
Static sound between sound playback

### ISSUE THREAD

**Issue by dansvend** [equinor/attenuation-app#78]
Use a longer sound file to reduce the number of replays of the sound file. A 1 minute long sound file would only make a static sound once a minute which most people will never hear since they continue to next step in the test plan before 1 minute.

**Comment by dansvend** [comment]
@QiJin-Bouvet This is ready for testing in `2024.821.108` 🧪

**Comment by QiJin-Bouvet** [comment]
Tested with the build above.
Static sound plays/replays good.
